#The default difficulty selected for newly created worlds.
#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
defaultDifficulty = "NORMAL"
#Resource pack IDs to have enabled by default on the first run.
defaultResourcePacks = ["vanilla", "fabric", "mod_resources", "moonlight:merged_pack", "aeronauticshotairfix:hot_air_fix", "file/CreateEasyVillager_v1.0.1a.zip", "file/CreateSophBackpacks.zip", "file/CreateSophStorage.zip", "file/Create_Simple_Storage_2.1+3D.zip", "file/Create_style_Fuctional_Storage-1.0.2.zip", "file/Creatified SOL Onion 1.0.zip", "file/ccc.zip", "file/create-trash-cans-1.2.zip", "scholar:colored_books", "scholar:chiseled_bookshelf_colored_books", "file/Mudpack"]
#Set to true if the difficulty for new world's should be locked to the specific default. This cannot be unlocked by players without external tools! Probably a bad idea. I don't recommend. Why am I adding this option?
lockDifficulty = false
