StartupEvents.registry('block', event => {
    event.create('cast_mould_blank')
        .displayName('Cast Mould Blank')
        .soundType('wood')
        .hardness(2.0)
        .resistance(2.0)
        .tagBlock('minecraft:mineable/axe')
        .fullBlock(true)
        .requiresTool(false)
        .texture('up', 'mud:block/cannon_mould_top')
        .texture('down', 'mud:block/cannon_mould_top')
        .texture('north', 'mud:block/cannon_mould_base')
        .texture('south', 'mud:block/cannon_mould_base')
        .texture('east', 'mud:block/cannon_mould_base')
        .texture('west', 'mud:block/cannon_mould_base')
})