
StartupEvents.registry('item', event => {
    //Glutinous Mass (Create Slime Overhaul)
    event.create('glutinous_mass')
        .displayName('Glutinous Mass')
        .texture('mud:item/glutinous_mass')
        .maxStackSize(64)
    
    event.create('incomplete_glutinous_mass')
        .displayName('Sticky Glutinous Mess')
        .texture('mud:item/incomplete_glutinous_mass')
        .maxStackSize(64)

    //Uranium Processing
        //Main Pre Line
        event.create('uranium_rich_gravel')
            .displayName('Uranium-Rich Gravel')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
       event.create('dense_uranium_rich_gravel')
            .displayName('Dense Uranium-Rich Gravel')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
       event.create('uranium_rich_slurry')
            .displayName('Uranium-Rich Slurry')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
        event.create('pitchblende')
            .displayName('Pitchblende')
            .texture('mud:item/pitchblende')
            .maxStackSize(64)
        event.create('tyuyayamunite')
            .displayName('Tyuyayamunite')
            .texture('mud:item/tyuyayamunite')
            .maxStackSize(64)
        //Offshoot Pre Line
        event.create('uranium_poor_tailings')
            .displayName('Uranium-Poor Tailings')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
        event.create('uranium_poor_slurry')
            .displayName('Uranium-Poor Slurry')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
        //Main Post Line
        event.create('brittle_uranium_rod')
            .displayName('Brittle Uranium Rod')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
        event.create('yellowgangue')
            .displayName('Yellowgangue')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
        event.create('yellowgravel')
            .displayName('Yellowgravel')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
        event.create('yellowslurry')
            .displayName('Yellowslurry')
            .texture('mud:item/placeholder')
            .maxStackSize(64)
    //

})